name: UltimateInventory
version: 1.7
author: Percyqaz
main: me.Percyqaz.UltimateInventory.UltimateInventory
api-version: '1.20'
softdepend: [ChestSort]
commands:
  uipickblock:
    description: Internal command for client mod pick block detection
    usage: /<command> <material>
permissions:
# TODO: Add premium permission for pick block
  ultimateinventory.pickblock:
    default: true  # Allow all players to use this internal command
  ultimateinventory.shulkerbox:
    default: false
  ultimateinventory.enderchest:
    default: false
  ultimateinventory.craftingtable:
    default: false
  ultimateinventory.smithingtable:
    default: false
  ultimateinventory.stonecutter:
    default: false
  ultimateinventory.grindstone:
    default: false
  ultimateinventory.cartographytable:
    default: false
  ultimateinventory.loom:
    default: false
  ultimateinventory.anvil:
    default: false
  ultimateinventory.enchantingtable:
    default: false